version: '3'

volumes:
  mongodata:

services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://admin:admin!@mongodb:27017/"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin!
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - mongo-compose-network

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin!
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - mongo-compose-network

  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge